baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'In My Trini Era'
theme = 'ananke'

[module]
    [[module.imports]]
        path = "github.com/theNewDynamic/gohugo-theme-ananke"
        